#!/usr/bin/env python3
"""Build docs/solutions/INDEX.md — a cheap first-pass lookup surface.

Walks a docs/solutions/ directory tree, leniently parses YAML frontmatter out
of each *.md file (regex/string based — no PyYAML dependency), and writes a
single INDEX.md at the directory root grouping entries by subdirectory.

Usage:
    python3 build_solutions_index.py [path/to/docs/solutions]

Idempotent: running it twice over an unchanged tree produces byte-identical
output. Stdlib only, Python 3.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

GENERATED_HEADER = (
    "<!-- GENERATED by lean-flow:lf-learn build_solutions_index.py "
    "— do not hand-edit; regenerate after adding/updating solutions -->"
)

MAX_TAGS = 4

# Matches a leading `---\n ... \n---` YAML frontmatter block at the top of a file.
FRONTMATTER_RE = re.compile(r"\A---\s*\n(.*?)\n---\s*\n?", re.DOTALL)


def strip_quotes(value: str) -> str:
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in ("'", '"'):
        value = value[1:-1]
    return value.strip()


def parse_scalar_field(frontmatter: str, key: str) -> str | None:
    """Pull a simple `key: value` scalar field from a frontmatter block.

    Lenient: tolerates quoted or unquoted values, ignores fields that are
    actually nested blocks (value empty / next line indented).
    """
    pattern = re.compile(rf"^{re.escape(key)}:[ \t]*(.*)$", re.MULTILINE)
    match = pattern.search(frontmatter)
    if not match:
        return None
    value = match.group(1).strip()
    if not value:
        return None
    # Skip block-list markers like `tags:` with values on following lines.
    if value in ("|", ">", "|-", ">-"):
        return None
    return strip_quotes(value)


def parse_list_field(frontmatter: str, key: str, limit: int | None = None) -> list[str]:
    """Pull a list-valued field, supporting both inline `[a, b]` and YAML
    block-list (`- a` on following indented lines) forms. Lenient/best-effort.
    """
    pattern = re.compile(rf"^{re.escape(key)}:[ \t]*(.*)$", re.MULTILINE)
    match = pattern.search(frontmatter)
    if not match:
        return []
    inline = match.group(1).strip()
    items: list[str] = []
    if inline.startswith("["):
        # Inline flow list, possibly spanning multiple lines up to the closing ].
        start = match.end(1)
        rest = inline
        if "]" not in rest:
            tail = frontmatter[start:]
            close_idx = tail.find("]")
            if close_idx != -1:
                rest = inline + tail[: close_idx + 1]
        rest = rest.strip()
        if rest.startswith("[") and "]" in rest:
            rest = rest[1 : rest.index("]")]
        for raw_item in rest.split(","):
            item = strip_quotes(raw_item)
            if item:
                items.append(item)
    elif not inline:
        # Possible YAML block list on the following indented lines.
        start = match.end(0)
        for line in frontmatter[start:].splitlines():
            if re.match(r"^\S", line):
                break  # dedented back out of the block
            stripped = line.strip()
            if stripped.startswith("- "):
                items.append(strip_quotes(stripped[2:]))
            elif stripped == "":
                continue
            else:
                break
    else:
        # Single bare scalar on the `key:` line itself.
        items.append(strip_quotes(inline))

    if limit is not None:
        items = items[:limit]
    return items


def extract_date_from_filename(filename: str) -> str | None:
    match = re.search(r"(\d{4}-\d{2}-\d{2})", filename)
    return match.group(1) if match else None


def fallback_title_from_body(body: str, filename: str) -> str:
    for line in body.splitlines():
        stripped = line.strip()
        if stripped.startswith("#"):
            return stripped.lstrip("#").strip()
    for line in body.splitlines():
        stripped = line.strip()
        if stripped:
            return stripped
    return filename


def build_entry(path: Path, root: Path) -> tuple[str, str, str]:
    """Return (relpath, title, summary_line) for one doc. Never raises —
    malformed frontmatter falls back to the filename.
    """
    relpath = path.relative_to(root).as_posix()
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return relpath, path.stem, ""

    frontmatter = ""
    body = text
    fm_match = FRONTMATTER_RE.match(text)
    if fm_match:
        frontmatter = fm_match.group(1)
        body = text[fm_match.end() :]

    title = None
    if frontmatter:
        title = parse_scalar_field(frontmatter, "title")
    if not title:
        title = fallback_title_from_body(body, path.stem)

    date = None
    if frontmatter:
        date = parse_scalar_field(frontmatter, "date") or parse_scalar_field(
            frontmatter, "last_updated"
        )
    if not date:
        date = extract_date_from_filename(path.name)

    tags: list[str] = []
    category = None
    if frontmatter:
        tags = parse_list_field(frontmatter, "tags", limit=MAX_TAGS)
        category = parse_scalar_field(frontmatter, "category")
        if not tags:
            problem_types = parse_list_field(frontmatter, "problem_type", limit=MAX_TAGS)
            tags = problem_types

    descriptor_parts = []
    if category:
        descriptor_parts.append(category)
    if tags:
        descriptor_parts.append("/".join(tags))
    descriptor = ", ".join(descriptor_parts) if descriptor_parts else "uncategorized"

    summary = descriptor
    if date:
        summary = f"{summary} ({date})"

    return relpath, title, summary


def collect_docs(root: Path) -> list[Path]:
    docs = [
        p
        for p in root.rglob("*.md")
        if p.name != "INDEX.md"
    ]
    return docs


def group_by_subdir(root: Path, docs: list[Path]) -> dict[str, list[Path]]:
    groups: dict[str, list[Path]] = {}
    for doc in docs:
        rel = doc.relative_to(root)
        subdir = rel.parts[0] if len(rel.parts) > 1 else "."
        groups.setdefault(subdir, []).append(doc)
    return groups


def render_index(root: Path) -> str:
    docs = collect_docs(root)
    groups = group_by_subdir(root, docs)

    lines = [GENERATED_HEADER, "", "# Solutions Index", ""]

    for subdir in sorted(groups.keys()):
        heading = subdir if subdir != "." else "(root)"
        lines.append(f"## {heading}")
        lines.append("")
        entries = sorted(groups[subdir], key=lambda p: p.name)
        for doc_path in entries:
            relpath, title, summary = build_entry(doc_path, root)
            lines.append(f"- [{title}]({relpath}) — {summary}")
        lines.append("")

    return "\n".join(lines).rstrip("\n") + "\n"


def main(argv: list[str]) -> int:
    target = Path(argv[1]) if len(argv) > 1 else Path("docs/solutions")
    if not target.is_dir():
        print(f"error: {target} is not a directory", file=sys.stderr)
        return 1

    content = render_index(target)
    index_path = target / "INDEX.md"
    index_path.write_text(content, encoding="utf-8")
    doc_count = len(collect_docs(target))
    print(f"Wrote {index_path} ({doc_count} docs indexed)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
